server:
  error:
      include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: INFO
mybatis:
  mapper-locations:
    - classpath:mybatis/**/*.xml