name: Theo - CI/CD

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm -i

      #- name: Build
      #  run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd TeamUp-PeerTutorApp/
            git pull origin main  # Pull latest changes
            pm2 restart theo  # Restart your Next.js app using pm2 or any other process manager
